base: &base
 database_prefix: 
 database_suffix: _<%= RAILS_ENV %>

development:
  host: localhost
  port: 5984
  <<: *base
  
test: &test
  host: localhost
  port: 5984
  <<: *base

cucumber:
  <<: *test
